### ISSUE TITLE
German letter issue

### ISSUE THREAD

**Issue by mario-to-lowercase** [robomaeyhem/PircBot2#10]
How can i display and send german symbols (ä,Ä,ö,Ö,ü;Ü and ß)?

**Comment by TheChef1337** [comment]
`sendMessage(channel,"ä,Ä,ö,Ö,ü;Ü and ß");` seems to work fine for me. Do you have your encoding set properly?
![javaw_2017-12-31_11-05-49](https://user-images.githubusercontent.com/3971213/34462856-cee9936c-ee1a-11e7-946d-eb8c4dee4fe5.png)

**Comment by mario-to-lowercase** [comment]
This is what it looks like when i try it:

![screen](https://user-images.githubusercontent.com/34585017/34648611-a298f438-f39c-11e7-89af-fd9b578e8b76.png)

EDIT: i forgot to set the encoding. works now thanks :)

**Comment by robomaeyhem** [comment]
What does your code look like?
