### ISSUE TITLE
Question about Consoleoutput

### ISSUE THREAD

**Issue by mario-to-lowercase** [robomaeyhem/PircBot2#11]
Hi
is it possible to dissable the console output for incomming messages?

I display all incomming messages with my own format and color and so i want to disable that.

You can see what i mean here:

![screenshot_1](https://user-images.githubusercontent.com/34585017/35492132-525d93d2-04ab-11e8-80cf-782cb28c8a00.png)

**Comment by TheChef1337** [comment]
You can use `setVerbose(false);` to disable those messages

**Comment by mario-to-lowercase** [comment]
Thans for the awnser :)
