### ISSUE TITLE
Whispers not received

### ISSUE THREAD

**Issue by lfdversluis** [robomaeyhem/PircBot2#9]
Hey, thanks for updating pircbot to be a little more up to date especially with Twitch.

It seems that the onWhisper is never called, I override the handleLine and I don't see the whisper coming there either, do you think this is Twitch's side or the bot having a bug?

**Comment by TheChef1337** [comment]
Just checked on my end with the latest version, and it works fine. Are you calling
`bot.sendRawLine("CAP REQ :twitch.tv/commands");`
when you initialize your bot? You'll need to do that in order to receive whispers.

**Comment by frumpy4** [comment]
Twitch's IRC implementation is weird, you need to request capabilities for receiving things such as JOIN/PART and other twitch-specific commands.

There's documentation on it here: https://github.com/justintv/Twitch-API/blob/master/IRC.md#twitch-capabilities

**Comment by lfdversluis** [comment]
Ahh Thanks @robomaeyhem, completely missed that. Perhaps it could be added to the readme of this repo since I think it's one of the major points this pircbot version offers :)
